### ISSUE TITLE
Issue when upgrading into RN 0.64

### ISSUE THREAD

**Issue by exneval** [th3rdwave/react-native-safe-area-context#185]
Just upgrade RN from 0.63.4 -> 0.64.0
And when built android, the app crashed upon opening, this is the log that been found

the package working fine in 0.63.4

```
java.lang.IncompatibleClassChangeError: Found class com.facebook.react.uimanager.events.EventDispatcher, but interface was expected (declaration of 'com.facebook.react.uimanager.events.EventDispatcher' appears in /data/app/path/to/project)
 at com.th3rdwave.safeareacontext.SafeAreaProviderManager$1.onInsetsChange(SafeAreaProviderManager.java:47)
 at com.th3rdwave.safeareacontext.SafeAreaProvider.maybeUpdateInsets(SafeAreaProvider.java:35)
 at com.th3rdwave.safeareacontext.SafeAreaProvider.onPreDraw(SafeAreaProvider.java:58)
 at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1088)
 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2978)
 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1888)
 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8043)
 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:969)
 at android.view.Choreographer.doCallbacks(Choreographer.java:793)
 at android.view.Choreographer.doFrame(Choreographer.java:728)
 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:954)
 at android.os.Handler.handleCallback(Handler.java:914)
 at android.os.Handler.dispatchMessage(Handler.java:100)
 at android.os.Looper.loop(Looper.java:224)
 at android.app.ActivityThread.main(ActivityThread.java:7551)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
```

**Comment by exneval** [comment]
After doing more research turn out it's not the react-native-safe-area-context issue, sorry

**Comment by neuneed** [comment]
> After doing more research turn out it's not the react-native-safe-area-context issue, sorry

Hi, I am facing the same issue when upgrade to RN 0.64, can you tell me that how to fix this issue？ thanks!

**Comment by exneval** [comment]
> > After doing more research turn out it's not the react-native-safe-area-context issue, sorry
> 
> Hi, I am facing the same issue when upgrade to RN 0.64, can you tell me that how to fix this issue？ thanks!

what I did jut update all packages version that I've used in the project

**Comment by neuneed** [comment]
> > > After doing more research turn out it's not the react-native-safe-area-context issue, sorry
> > 
> > 
> > Hi, I am facing the same issue when upgrade to RN 0.64, can you tell me that how to fix this issue？ thanks!
> 
> what I did jut update all packages version that I've used in the project

ok will try that too thanks!

**Comment by ruinername** [comment]
@Svarto Hi! Did you find out reason of crash? Have same error now :(

**Comment by Svarto** [comment]
@ruinername hmm, good question, went through my logs and can't see what I did. I remember going through and trying different safe area changes but wasnt it. Might have been that another package wasn't updates yet? Sorry I can't be of more help
