### ISSUE TITLE
Android: `java.lang.IllegalMonitorStateException` on application startup

### ISSUE THREAD

**Issue by fiznool** [th3rdwave/react-native-safe-area-context#247]
I've recently upgraded an existing project to React Native 0.67.3, and in the process upgraded this library from 3.3.2 to 4.1.0. After fully cleaning the project (using `react-native-clean-project`) and reinstalling all dependencies, I'm getting the following exception when running my app on Android in debug mode:

```
03-01 11:15:38.784 17165 17658 E unknown:ReactNative: Exception in native call
03-01 11:15:38.784 17165 17658 E unknown:ReactNative: java.lang.IllegalMonitorStateException
03-01 11:15:38.784 17165 17658 E unknown:ReactNative: 	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.signal(AbstractQueuedSynchronizer.java:1967)
03-01 11:15:38.784 17165 17658 E unknown:ReactNative: 	at com.th3rdwave.safeareacontext.SafeAreaView.waitForReactLayout$lambda-1(SafeAreaView.kt:65)
03-01 11:15:38.784 17165 17658 E unknown:ReactNative: 	at com.th3rdwave.safeareacontext.SafeAreaView.lambda$v23MVNlCq6E_9NrmCTiNPvStV4w(Unknown Source:0)
03-01 11:15:38.784 17165 17658 E unknown:ReactNative: 	at com.th3rdwave.safeareacontext.-$$Lambda$SafeAreaView$v23MVNlCq6E_9NrmCTiNPvStV4w.run(Unknown Source:4)
03-01 11:15:38.784 17165 17658 E unknown:ReactNative: 	at android.os.Handler.handleCallback(Handler.java:938)
03-01 11:15:38.784 17165 17658 E unknown:ReactNative: 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-01 11:15:38.784 17165 17658 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
03-01 11:15:38.784 17165 17658 E unknown:ReactNative: 	at android.os.Looper.loop(Looper.java:246)
03-01 11:15:38.784 17165 17658 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
03-01 11:15:38.784 17165 17658 E unknown:ReactNative: 	at java.lang.Thread.run(Thread.java:923)
```

I'm unable to share the source code of the project in question, however the Android implementation uses `react-native-navigation` and a couple of custom Android native modules, to speak to a hardware device. This has necessitated a few changes to the native Android code, which I guess could be causing the issue here.

For now I'm going back to 3.3.2 as I don't know how to debug this issue any further, but please let me know if I can provide any further information to help try and reproduce this.

**Comment by janicduplessis** [comment]
Can you test 4.1.1, it should fix the issue.
