### ISSUE TITLE
Help Wanted with jest snapshot test when using SafeAreaView

### ISSUE THREAD

**Issue by FlipThibault** [th3rdwave/react-native-safe-area-context#328]
I'm currently rending a component (named LoginModal) that uses a SafeAreaView. 

```
<SafeAreaView edges={['top']} style={{ paddingTop: 100 }}>
//children
</SafeAreaView>
```
However, when trying to run my tests I run into the following error: 

```
 Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

    Check the render method of `LoginModal`.

      at createFiberFromTypeAndProps (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:16180:21)
      at createFiberFromElement (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:16208:15)
      at reconcileSingleElement (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5358:23)
      at mountChildFibers (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5418:35)
      at reconcileChildren (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7984:28)
      at mountIndeterminateComponent (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8810:5)
      at beginWork$1 (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9966:16)
      at performUnitOfWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13800:12)
      at workLoopSync (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13728:5)
      at renderRootSync (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13691:7)
```

I've also added the following to my setup files:
```
import mockSafeAreaContext from 'react-native-safe-area-context/jest/mock';
jest.mock('react-native-safe-area-context', () => mockSafeAreaContext);
```
and the test itself contains the following relevant code:

```
import React from 'react';
import renderer from 'react-test-renderer';

import LoginModal from '~components/Login/LoginModal.component';

describe('LoginModal Component Tests', () => {

  test('snapshot test default - login', () => {

    const tree = renderer.create(<LoginModal />).toJSON();

    expect(tree).toMatchSnapshot();

  });

});
```

I'm wondering if anyone can help point me in the right direction of what may be missing in terms of setup or if there may be anyone else running into similar issues. 

Thank you!

**Comment by jacobp100** [comment]
Please continue discussion https://github.com/th3rdwave/react-native-safe-area-context/pull/231
