### ISSUE TITLE
react-native-safe-area-context:generateCodegenArtifactsFromSchema FAILED

### ISSUE THREAD

**Issue by FedeBev** [th3rdwave/react-native-safe-area-context#362]
Hi there,

my build is failing with the following error

```
.../node_modules/react-native-codegen/lib/generators/modules/GenerateModuleJniCpp.js:460
        return moduleNames.map(moduleName => ({
                           ^

TypeError: Cannot read properties of undefined (reading 'map')
    at .../node_modules/react-native-codegen/lib/generators/modules/GenerateModuleJniCpp.js:460:28
    at Array.flatMap (<anonymous>)
    at generate (.../node_modules/react-native-codegen/lib/generators/modules/GenerateModuleJniCpp.js:457:8)
    at Object.generate (.../node_modules/react-native-codegen/lib/generators/RNCodegen.js:165:9)
    at Object.generateSpec [as execute] (.../node_modules/react-native/scripts/codegen/generate-specs-cli-executor.js:97:13)
    at main (.../node_modules/react-native/scripts/generate-specs-cli.js:51:12)
    at Object.<anonymous> (.../node_modules/react-native/scripts/generate-specs-cli.js:61:1)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
 ```
 
 This is what   `react-native-codegen` is tying to do
 
 ```js
    const moduleNames = nativeModules[hasteModuleName].moduleNames;
        return moduleNames.map(moduleName => ({
          moduleName,
          hasteModuleName,
        }));
      });
 ```
 
 but `nativeModules[hasteModuleName]` is the following (field `moduleNames` is not there)
 
 ```js
 {
  type: 'NativeModule',
  aliasMap: {},
  enumMap: {},
  spec: { properties: [ [Object] ] },
  moduleName: 'RNCSafeAreaContext'
}
```

## ENV info

```
npx react-native info
info Fetching system and libraries information...
System:
    OS: Linux 5.19 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
    Memory: 10.83 GB / 31.14 GB
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 19.7.0 - /usr/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 9.5.0 - /usr/bin/npm
    Watchman: 20221126.133621.0 - /usr/local/bin/watchman
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 17.0.6 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.3 => 0.71.3 
  npmGlobalPackages:
    *react-native*: Not Found
    
    
  @react-native/codegen: 0.72.3
  react-native-safe-area-context:  4.5.0
 ```
 
 Thanks!

**Comment by jacobp100** [comment]
What's making you think it's this library causing it?

**Comment by FedeBev** [comment]
Hey @jacobp100, thanks for your quick reply

this part here

```
but nativeModules[hasteModuleName] is the following (field moduleNames is not there)

{
 type: 'NativeModule',
 aliasMap: {},
 enumMap: {},
 spec: { properties: [ [Object] ] },
 moduleName: 'RNCSafeAreaContext'
}
```

**Comment by jacobp100** [comment]
Are you using the new architecture?

**Comment by jacobp100** [comment]
I'm closing this due to inactivity - but feel free to continue the discussion here

**Comment by devinhadley** [comment]
I have the same issue.
