### ISSUE TITLE
Upgrade from 0.6.4 to 0.7.0 break my app

### ISSUE THREAD

**Issue by kopax** [th3rdwave/react-native-safe-area-context#49]
react-native-safe-area-context            0.6.4  →         0.7.0 

After trying this upgrade, I am having test issue with jest:

```
    TypeError: Cannot read property 'Constants' of undefined

      at Object.<anonymous> (node_modules/react-native-safe-area-context/lib/commonjs/InitialWindowSafeAreaInsets.ts:9:17)
      at Object.<anonymous> (node_modules/react-native-safe-area-context/lib/commonjs/index.tsx:6:1)
```

I expect them to pass as in with 0.6.4.

Thanks!

**Comment by janicduplessis** [comment]
Sorry about that, fixed in 0.7.1
