### ISSUE TITLE
E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules

### ISSUE THREAD

**Issue by codecog** [th3rdwave/react-native-safe-area-context#55]
This happens intermittently on app load, not to sure exactly as too why.

v0.7.2

```
    java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.WindowInsets.getSystemWindowInsetTop()' on a null object reference
        at com.th3rdwave.safeareacontext.SafeAreaUtils.getSafeAreaInsets(SafeAreaUtils.java:47)
        at com.th3rdwave.safeareacontext.SafeAreaViewManager.getExportedViewConstants(SafeAreaViewManager.java:69)
        at com.facebook.react.uimanager.UIManagerModuleConstantsHelper.createConstantsForViewManager(UIManagerModuleConstantsHelper.java:134)
        at com.facebook.react.uimanager.UIManagerModuleConstantsHelper.createConstants(UIManagerModuleConstantsHelper.java:93)
        at com.facebook.react.uimanager.UIManagerModule.createConstants(UIManagerModule.java:275)
        at com.facebook.react.uimanager.UIManagerModule.<init>(UIManagerModule.java:182)
        at com.facebook.react.uimanager.UIManagerModule.<init>(UIManagerModule.java:143)
        at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:184)
        at com.facebook.react.CoreModulesPackage.getModule(CoreModulesPackage.java:152)
        at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:122)
        at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:110)
        at com.facebook.react.bridge.ModuleHolder.create(ModuleHolder.java:188)
        at com.facebook.react.bridge.ModuleHolder.getModule(ModuleHolder.java:153)
        at com.facebook.react.bridge.NativeModuleRegistry.getModule(NativeModuleRegistry.java:148)
        at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:479)
        at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:466)
        at com.facebook.react.uimanager.UIManagerHelper.getUIManager(UIManagerHelper.java:31)
        at com.facebook.react.ReactInstanceManager.attachRootViewToInstance(ReactInstanceManager.java:1054)
        at com.facebook.react.ReactInstanceManager.setupReactContext(ReactInstanceManager.java:1012)
        at com.facebook.react.ReactInstanceManager.access$1400(ReactInstanceManager.java:125)
        at com.facebook.react.ReactInstanceManager$5$2.run(ReactInstanceManager.java:972)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
        at android.os.Looper.loop(Looper.java:214)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
        at java.lang.Thread.run(Thread.java:919)
```

**Comment by Kauhsa** [comment]
Happens to us as well. As mentioned in my duplicate issue, currently we seem to be able to reproduce this reliably by first starting the application, then closing it by swiping it on recent apps view and then starting the application again (at which point it crashes).

**Comment by codecog** [comment]
Yup. First install it crashes, then nothing until switching apps and then coming back, will likely crash again.

**Comment by RafaelSNascimento** [comment]
O mesmo aqui, aparentemente isso está acontecendo no Android 10.
Eu tive 16 erros hoje, só no Android 10 e só trava após o primeiro aberto após a instalação.



`java.lang.NullPointerException: 
  at com.th3rdwave.safeareacontext.SafeAreaUtils.getSafeAreaInsets (SafeAreaUtils.java:47)
  at com.th3rdwave.safeareacontext.SafeAreaViewManager.getExportedViewConstants (SafeAreaViewManager.java:69)
  at com.facebook.react.uimanager.UIManagerModuleConstantsHelper.createConstantsForViewManager (UIManagerModuleConstantsHelper.java:134)
  at com.facebook.react.uimanager.UIManagerModuleConstantsHelper.createConstants (UIManagerModuleConstantsHelper.java:93)
  at com.facebook.react.uimanager.UIManagerModule.createConstants (UIManagerModule.java:275)
  at com.facebook.react.uimanager.UIManagerModule.<init> (UIManagerModule.java:182)
  at com.facebook.react.uimanager.UIManagerModule.<init> (UIManagerModule.java:143)
  at com.facebook.react.CoreModulesPackage.createUIManager (CoreModulesPackage.java:184)
  at com.facebook.react.CoreModulesPackage.getModule (CoreModulesPackage.java:152)
  at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get (TurboReactPackage.java:122)
  at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get (TurboReactPackage.java:110)
  at com.facebook.react.bridge.ModuleHolder.create (ModuleHolder.java:188)
  at com.facebook.react.bridge.ModuleHolder.getModule (ModuleHolder.java:153)
  at com.facebook.react.bridge.NativeModuleRegistry.getModule (NativeModuleRegistry.java:148)
  at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule (CatalystInstanceImpl.java:479)
  at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule (CatalystInstanceImpl.java:466)
  at com.facebook.react.uimanager.UIManagerHelper.getUIManager (UIManagerHelper.java:31)
  at com.facebook.react.ReactInstanceManager.attachRootViewToInstance (ReactInstanceManager.java:1054)
  at com.facebook.react.ReactInstanceManager.setupReactContext (ReactInstanceManager.java:1012)
  at com.facebook.react.ReactInstanceManager.access$1400 (ReactInstanceManager.java:125)
  at com.facebook.react.ReactInstanceManager$5$2.run (ReactInstanceManager.java:972)
  at android.os.Handler.handleCallback (Handler.java:883)
  at android.os.Handler.dispatchMessage (Handler.java:100)
  at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage (MessageQueueThreadHandler.java:26)
  at android.os.Looper.loop (Looper.java:241)
  at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run (MessageQueueThreadImpl.java:225)
  at java.lang.Thread.run (Thread.java:919)`

**Comment by janicduplessis** [comment]
Thanks for the report! Published a fix to handle this null value in `0.7.3`

**Comment by JoeLeung32** [comment]
I got error on 0.7.3 in Android build.
The specified project directory '..../node_modules/react-native-safe-area-context/example/android' does not exist.

So I downgrade to 0.7.2.

**Comment by RafaelSNascimento** [comment]
> I got error on 0.7.3 in Android build.
> The specified project directory '..../node_modules/react-native-safe-area-context/example/android' does not exist.
> 
> So I downgrade to 0.7.2.
> ![Screenshot 2020-03-02 at 6 49 18 PM](https://user-images.githubusercontent.com/37429278/75669878-be04a480-5cb6-11ea-9d11-5d70c1de1309.png)

Update to 0.7.3 and try remove node_modules folder, run npm cache clear -f and run npm install again.

**Comment by JoeLeung32** [comment]
> > I got error on 0.7.3 in Android build.
> > The specified project directory '..../node_modules/react-native-safe-area-context/example/android' does not exist.
> > So I downgrade to 0.7.2.
> > ![Screenshot 2020-03-02 at 6 49 18 PM](https://user-images.githubusercontent.com/37429278/75669878-be04a480-5cb6-11ea-9d11-5d70c1de1309.png)
> 
> Update to 0.7.3 and try remove node_modules folder, run npm cache clear -f and run npm install again.

Thx @RafaelSNascimento, it is work :-)

**Comment by Nikooos** [comment]
I'm seeing this coming round in 3.3.2. Anyone else having this as well?
