### ISSUE TITLE
jest mock and RN 0.76.1: TypeError: NativeModule.getConstants is not a function

### ISSUE THREAD

**Issue by andreialecu** [th3rdwave/react-native-safe-area-context#550]
After upgrading to RN 0.76.1, the jest mock seems to fail to import:

```

    TypeError: NativeModule.getConstants is not a function


    >  9 | import mockSafeAreaContext from 'react-native-safe-area-context/jest/mock';
         | ^


      at Object.getConstants (node_modules/react-native/src/private/specs/modules/NativeDeviceInfo.js:52:32)
      at Object.getConstants (node_modules/react-native/Libraries/Utilities/Dimensions.js:121:33)
      at Object.require (node_modules/react-native/Libraries/Utilities/PixelRatio.js:13:20)
      at Object.require (node_modules/react-native/Libraries/StyleSheet/StyleSheet.js:29:20)
      at Object.require [as StyleSheet] (node_modules/react-native/index.js:306:12)
      at Object.StyleSheet (node_modules/react-native-safe-area-context/lib/commonjs/SafeAreaContext.js:77:29)
      at Object.require (node_modules/react-native-safe-area-context/lib/commonjs/index.js:7:24)
      at Object.requireActual (node_modules/react-native-safe-area-context/jest/mock.tsx:25:32)
      at Object.require (jest.setup.js:9:1)
```

**Comment by paulschreiber** [comment]
We're seeing the same thing:
https://github.com/techmatters/terraso-mobile-client/actions/runs/11842140912/job/33000063351

In our case, I don't see `react-native-safe-area-context` in the stack trace.

**Comment by Balthazar33** [comment]
I got this for `react-native-mmkv-storage`.
Sharing the mmkv mock here, in case anyone needs it:

```
jest.mock('react-native-mmkv-storage', () => {
  return {
    MMKVLoader: jest.fn().mockImplementation(() => {
      return {
        withInstanceID: jest.fn().mockReturnValue({
          initialize: jest.fn().mockResolvedValue({
            setString: jest.fn(),
            getString: jest.fn(),
            removeItem: jest.fn(),
            clearStore: jest.fn(),
            getAllKeys: jest.fn(),
          }),
        }),
        initialize: jest.fn().mockResolvedValue({
          setString: jest.fn(),
          getString: jest.fn(),
          removeItem: jest.fn(),
          clearStore: jest.fn(),
          getAllKeys: jest.fn(),
        }),
      };
    }),
  };
});
```

Also, I did **not** add the library's setUp file path in `setupFiles` in my `jest.config` file, but appended the package name to `transformIgnorePatterns`.

 I added the mock I've shared above in my `jestSetup.js` file which has the mocks for the whole app.

**Comment by yoohaso** [comment]
> A PR would be helpful if anyone fancies it

@jacobp100 Hi, Can i work on this?

**Comment by yoohaso** [comment]
@andreialecu I'm trying to verify if this issue still occurs in the current version. Could you confirm if you're still experiencing this issue with React Native 0.76.1 or has it been resolved in newer versions?

**Comment by camboYY** [comment]
Test suite failed to run

    TypeError: NativeModule.getConstants is not a function

       9 |   const CURRENCY_CODE_KHR = 'KHR';
      10 |
    > 11 |   return {
         |   ^
      12 |     ...RN,
      13 |
      14 |     /* ✅ FIX: StyleSheet */

      at Object.getConstants (node_modules/react-native/src/private/specs_DEPRECATED/modules/NativeDeviceInfo.js:53:32)
      at Object.getConstants (node_modules/react-native/Libraries/Utilities/Dimensions.js:126:33)
      at Object.require (node_modules/react-native/Libraries/Utilities/PixelRatio.js:13:20)
      at Object.require (node_modules/react-native/Libraries/StyleSheet/StyleSheetExports.js:20:20)
      at Object.require (node_modules/react-native/Libraries/StyleSheet/StyleSheet.js:30:3)
      at Object.require (node_modules/react-native/Libraries/Components/ActivityIndicator/ActivityIndicator.js:15:1)
      at requireActual (node_modules/react-native/jest/mockComponent.js:36:12)
      at Object.mockComponent (node_modules/react-native/jest/mocks/ActivityIndicator.js:17:27)
      at requireActual (node_modules/react-native/jest/mock.js:32:44)
      at Object.require [as ActivityIndicator] (node_modules/react-native/index.js:35:12)

**Comment by huytdps13400** [comment]
Implemented in #760. The built-in mock no longer evaluates the real package or React Native native runtime during import, so it cannot reach the missing `NativeDeviceInfo.getConstants()` path.

The replacement preserves the runtime export surface and custom provider metrics. Verification: 6 Jest suites / 26 tests / 11 snapshots pass, TypeScript and Bob builds pass, and lint has no new errors.
