### ISSUE TITLE
0.7.2 sometimes crashes on boot on Android

### ISSUE THREAD

**Issue by Kauhsa** [th3rdwave/react-native-safe-area-context#56]
I don't know more yet, but we get a crash with the following stacktrace... sometimes. Has happened at least on two different devices (OnePlus 3T and Nexus 5X). Seems to happen when the application is first started, then closed by swiping it on recent apps view and then starting the application again results a crash.

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.WindowInsets.getSystemWindowInsetTop()' on a null object reference
	at com.th3rdwave.safeareacontext.SafeAreaUtils.getSafeAreaInsets(SafeAreaUtils.java:47)
	at com.th3rdwave.safeareacontext.SafeAreaViewManager.getExportedViewConstants(SafeAreaViewManager.java:69)
	at com.facebook.react.uimanager.UIManagerModuleConstantsHelper.createConstantsForViewManager(UIManagerModuleConstantsHelper.java:134)
	at com.facebook.react.uimanager.UIManagerModuleConstantsHelper.createConstants(UIManagerModuleConstantsHelper.java:93)
	at com.facebook.react.uimanager.UIManagerModule.createConstants(UIManagerModule.java:275)
	at com.facebook.react.uimanager.UIManagerModule.<init>(UIManagerModule.java:182)
	at com.facebook.react.uimanager.UIManagerModule.<init>(UIManagerModule.java:143)
	at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:184)
	at com.facebook.react.CoreModulesPackage.getModule(CoreModulesPackage.java:152)
	at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:122)
	at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:110)
	at com.facebook.react.bridge.ModuleHolder.create(ModuleHolder.java:188)
	at com.facebook.react.bridge.ModuleHolder.getModule(ModuleHolder.java:153)
	at com.facebook.react.bridge.NativeModuleRegistry.getModule(NativeModuleRegistry.java:148)
	at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:479)
	at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:466)
	at com.facebook.react.uimanager.UIManagerHelper.getUIManager(UIManagerHelper.java:31)
	at com.facebook.react.ReactInstanceManager.attachRootViewToInstance(ReactInstanceManager.java:1054)
	at com.facebook.react.ReactInstanceManager.setupReactContext(ReactInstanceManager.java:1012)
	at com.facebook.react.ReactInstanceManager.access$1400(ReactInstanceManager.java:125)
	at com.facebook.react.ReactInstanceManager$5$2.run(ReactInstanceManager.java:972)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
	at android.os.Looper.loop(Looper.java:193)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
	at java.lang.Thread.run(Thread.java:764)
```

I'll update if/when I get more details.

**Comment by Kauhsa** [comment]
My bad, duplicate of #55.
