### ISSUE TITLE
NullpointerException when Android first open app.

### ISSUE THREAD

**Issue by keepcosmos** [th3rdwave/react-native-safe-area-context#59]
Only on Android,  It raise Nullpointer Exception when launch an app,
Especially, a single ~ twice times just after resintall or upgrade.

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.WindowInsets.getSystemWindowInsetTop()' on a null object reference
       at com.th3rdwave.safeareacontext.SafeAreaUtils.getSafeAreaInsets(SafeAreaUtils.java:48)
       at com.th3rdwave.safeareacontext.SafeAreaViewManager.getExportedViewConstants(SafeAreaViewManager.java:69)
       at com.facebook.react.uimanager.UIManagerModuleConstantsHelper.createConstantsForViewManager(UIManagerModuleConstantsHelper.java:134)
       at com.facebook.react.uimanager.UIManagerModuleConstantsHelper.createConstants(UIManagerModuleConstantsHelper.java:93)
       at com.facebook.react.uimanager.UIManagerModule.createConstants(UIManagerModule.java:275)
       at com.facebook.react.uimanager.UIManagerModule.<init>(UIManagerModule.java:182)
       at com.facebook.react.uimanager.UIManagerModule.<init>(UIManagerModule.java:143)
       at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:184)
       at com.facebook.react.CoreModulesPackage.getModule(CoreModulesPackage.java:152)
       at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:122)
       at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:110)
       at com.facebook.react.bridge.ModuleHolder.create(ModuleHolder.java:188)
       at com.facebook.react.bridge.ModuleHolder.getModule(ModuleHolder.java:153)
       at com.facebook.react.bridge.NativeModuleRegistry.getModule(NativeModuleRegistry.java:148)
       at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:479)
       at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:466)
       at com.facebook.react.uimanager.UIManagerHelper.getUIManager(UIManagerHelper.java:31)
       at com.facebook.react.ReactInstanceManager.attachRootViewToInstance(ReactInstanceManager.java:1054)
       at com.facebook.react.ReactInstanceManager.setupReactContext(ReactInstanceManager.java:1012)
       at com.facebook.react.ReactInstanceManager.access$1400(ReactInstanceManager.java:125)
       at com.facebook.react.ReactInstanceManager$5$2.run(ReactInstanceManager.java:972)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
       at android.os.Looper.loop(Looper.java:237)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
       at java.lang.Thread.run(Thread.java:919)
```

**Comment by dehypnosis** [comment]
how did you resolved this?
