### ISSUE TITLE
App crashes after updating to 1.0.0

### ISSUE THREAD

**Issue by Relax594** [th3rdwave/react-native-safe-area-context#71]
0.7.3 was fine. After the update to 1.0.0 app crashes upon every start.

```
System:
     OS: Windows 8.1 6.3.9600
     CPU: (8) x64 Intel(R) Xeon(R) CPU           E5630  @ 2.53GHz
     Memory: 38.13 GB / 48.00 GB
  Binaries:
    Node: 12.16.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 23, 28, 29
      Build Tools: 28.0.3, 29.0.3
      System Images: android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6392135
  Languages:
    Java: Not Found
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found
```

App.js:

```
import { SafeAreaProvider } from 'react-native-safe-area-context';
const App = () => {
return (
 <SafeAreaProvider>
     <View style={{ flex: 1 }}>
         <StatusBar barStyle="light-content" backgroundColor={Colors.statusBar} />
         <AppRoot style={{ flex: 1 }} />
     </View>
 </SafeAreaProvider>
)}
```

Crash Log:

```
2020-05-12 07:56:05.098 5196-5291/de.wrz.haustraum A/libc: Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 5291 (mqt_js), pid 5196 (e.wrz.haustraum)
2020-05-12 07:56:05.336 5312-5312/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
2020-05-12 07:56:05.336 5312-5312/? A/DEBUG: Build fingerprint: 'samsung/gts4lvwifieea/gts4lvwifi:9/PPR1.180610.011/T720XXS1ATC5:user/release-keys'
2020-05-12 07:56:05.336 5312-5312/? A/DEBUG: Revision: '5'
2020-05-12 07:56:05.337 5312-5312/? A/DEBUG: ABI: 'arm64'
2020-05-12 07:56:05.337 5312-5312/? A/DEBUG: pid: 5196, tid: 5291, name: mqt_js  >>> de.wrz.haustraum <<<
2020-05-12 07:56:05.337 5312-5312/? A/DEBUG: signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
2020-05-12 07:56:05.337 5312-5312/? A/DEBUG:     x0  0000000000000000  x1  00000000000014ab  x2  0000000000000006  x3  0000000000000008
2020-05-12 07:56:05.337 5312-5312/? A/DEBUG:     x4  fefeff041f3c9b0a  x5  fefeff041f3c9b0a  x6  fefeff041f3c9b0a  x7  7f7f7f7f7f7fff7f
2020-05-12 07:56:05.337 5312-5312/? A/DEBUG:     x8  0000000000000083  x9  6e8baa80f0a3624b  x10 0000000000000000  x11 fffffffc7ffffbdf
2020-05-12 07:56:05.337 5312-5312/? A/DEBUG:     x12 0000000000000001  x13 0000000000000000  x14 ffffffffffffffff  x15 0000007d14e47d90
2020-05-12 07:56:05.337 5312-5312/? A/DEBUG:     x16 0000007db7fdf298  x17 0000007db7f000fc  x18 0000000000000000  x19 000000000000144c
2020-05-12 07:56:05.337 5312-5312/? A/DEBUG:     x20 00000000000014ab  x21 0000000000000001  x22 0000007d1523435c  x23 0000007d14e4b588
2020-05-12 07:56:05.337 5312-5312/? A/DEBUG:     x24 0000000000000000  x25 0000000000000001  x26 0000007d12429800  x27 0000007d15cd5fd8
2020-05-12 07:56:05.337 5312-5312/? A/DEBUG:     x28 0000007d122701fc  x29 0000007d14e47d90
2020-05-12 07:56:05.337 5312-5312/? A/DEBUG:     sp  0000007d14e47d50  lr  0000007db7ef25cc  pc  0000007db7ef25f4
2020-05-12 07:56:05.413 5312-5312/? A/DEBUG: backtrace:
2020-05-12 07:56:05.413 5312-5312/? A/DEBUG:     #00 pc 00000000000225f4  /system/lib64/libc.so (abort+116)
2020-05-12 07:56:05.413 5312-5312/? A/DEBUG:     #01 pc 00000000000b8124  /data/app/de.wrz.haustraum-EYwCMySKegD9LZqUkC8B5w==/lib/arm64/libc++_shared.so
2020-05-12 07:56:05.413 5312-5312/? A/DEBUG:     #02 pc 00000000000b43d4  /data/app/de.wrz.haustraum-EYwCMySKegD9LZqUkC8B5w==/lib/arm64/libc++_shared.so (__gxx_personality_v0+364)
2020-05-12 07:56:05.413 5312-5312/? A/DEBUG:     #03 pc 000000000003b398  /data/app/de.wrz.haustraum-EYwCMySKegD9LZqUkC8B5w==/lib/arm64/libhermes-executor-debug.so
2020-05-12 07:56:05.413 5312-5312/? A/DEBUG:     #04 pc 000000000003b8a0  /data/app/de.wrz.haustraum-EYwCMySKegD9LZqUkC8B5w==/lib/arm64/libhermes-executor-debug.so (_Unwind_Resume+116)
2020-05-12 07:56:05.413 5312-5312/? A/DEBUG:     #05 pc 0000000000026c5c  /data/app/de.wrz.haustraum-EYwCMySKegD9LZqUkC8B5w==/lib/arm64/libhermes-executor-debug.so (facebook::react::JSIExecutor::callNativeModules(facebook::jsi::Value const&, bool)+224)
2020-05-12 07:56:05.413 5312-5312/? A/DEBUG:     #06 pc 0000000000028804  /data/app/de.wrz.haustraum-EYwCMySKegD9LZqUkC8B5w==/lib/arm64/libhermes-executor-debug.so
2020-05-12 07:56:05.413 5312-5312/? A/DEBUG:     #07 pc 0000000000020c18  /data/app/de.wrz.haustraum-EYwCMySKegD9LZqUkC8B5w==/lib/arm64/libhermes-executor-debug.so (std::__ndk1::__function::__func<facebook::jsi::DecoratedHostFunction, std::__ndk1::allocator<facebook::jsi::DecoratedHostFunction>, facebook::jsi::Value (facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)>::operator()(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*&&, unsigned long&&)+68)
2020-05-12 07:56:05.413 5312-5312/? A/DEBUG:     #08 pc 0000000000030238  /data/app/de.wrz.haustraum-EYwCMySKegD9LZqUkC8B5w==/lib/arm64/libhermes.so
2020-05-12 07:56:05.413 5312-5312/? A/DEBUG:     #09 pc 000000000004ca10  /data/app/de.wrz.haustraum-EYwCMySKegD9LZqUkC8B5w==/lib/arm64/libhermes.so
2020-05-12 07:56:05.413 5312-5312/? A/DEBUG:     #10 pc 000000000004faf0  /data/app/de.wrz.haustraum-EYwCMySKegD9LZqUkC8B5w==/lib/arm64/libhermes.so
2020-05-12 07:56:05.413 5312-5312/? A/DEBUG:     #11 pc 0000000000051ca4  /data/app/de.wrz.haustraum-EYwCMySKegD9LZqUkC8B5w==/lib/arm64/libhermes.so
2020-05-12 07:56:05.413 5312-5312/? A/DEBUG:     #12 pc 000000000003d578  /data/app/de.wrz.haustraum-EYwCMySKegD9LZqUkC8B5w==/lib/arm64/libhermes.so
2020-05-12 07:56:05.413 5312-5312/? A/DEBUG:     #13 pc 000000000004ca6c  /data/app/de.wrz.haustraum-EYwCMySKegD9LZqUkC8B5w==/lib/arm64/libhermes.so
2020-05-12 07:56:05.413 5312-5312/? A/DEBUG:     #14 pc 000000000004faf0  /data/app/de.wrz.haustraum-EYwCMySKegD9LZqUkC8B5w==/lib/arm64/libhermes.so
2020-05-12 07:56:05.413 5312-5312/? A/DEBUG:     #15 pc 0000000000051ca4  /data/app/de.wrz.haustraum-EYwCMySKegD9LZqUkC8B5w==/lib/arm64/libhermes.so
2020-05-12 07:56:05.413 5312-5312/? A/DEBUG:     #16 pc 000000000003c3fc  /data/app/de.wrz.haustraum-EYwCMySKegD9LZqUkC8B5w==/lib/arm64/libhermes.so
2020-05-12 07:56:05.413 5312-5312/? A/DEBUG:     #17 pc 00000000000d0dcc  /data/app/de.wrz.haustraum-EYwCMySKegD9LZqUkC8B5w==/lib/arm64/libhermes.so
2020-05-12 07:56:05.414 5312-5312/? A/DEBUG:     #18 pc 000000000004ca10  /data/app/de.wrz.haustraum-EYwCMySKegD9LZqUkC8B5w==/lib/arm64/libhermes.so
2020-05-12 07:56:05.414 5312-5312/? A/DEBUG:     #19 pc 000000000004faf0  /data/app/de.wrz.haustraum-EYwCMySKegD9LZqUkC8B5w==/lib/arm64/libhermes.so
2020-05-12 07:56:05.414 5312-5312/? A/DEBUG:     #20 pc 0000000000051ca4  /data/app/de.wrz.haustraum-EYwCMySKegD9LZqUkC8B5w==/lib/arm64/libhermes.so
2020-05-12 07:56:05.414 5312-5312/? A/DEBUG:     #21 pc 000000000003d578  /data/app/de.wrz.haustraum-EYwCMySKegD9LZqUkC8B5w==/lib/arm64/libhermes.so
2020-05-12 07:56:05.414 5312-5312/? A/DEBUG:     #22 pc 0000000000029530  /data/app/de.wrz.haustraum-EYwCMySKegD9LZqUkC8B5w==/lib/arm64/libhermes.so (facebook::hermes::HermesRuntimeImpl::call(facebook::jsi::Function const&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)+568)
2020-05-12 07:56:05.414 5312-5312/? A/DEBUG:     #23 pc 0000000000028ec4  /data/app/de.wrz.haustraum-EYwCMySKegD9LZqUkC8B5w==/lib/arm64/libhermes-executor-debug.so (_ZNK8facebook3jsi8Function4callIJRKNSt6__ndk112basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEESB_NS0_5ValueEEEESC_RNS0_7RuntimeEDpOT_+240)
2020-05-12 07:56:05.414 5312-5312/? A/DEBUG:     #24 pc 0000000000028d20  /data/app/de.wrz.haustraum-EYwCMySKegD9LZqUkC8B5w==/lib/arm64/libhermes-executor-debug.so
2020-05-12 07:56:05.414 5312-5312/? A/DEBUG:     #25 pc 0000000000023e70  /data/app/de.wrz.haustraum-EYwCMySKegD9LZqUkC8B5w==/lib/arm64/libhermes-executor-debug.so (_ZNSt6__ndk128__invoke_void_return_wrapperIvE6__callIJRPFvRKNS_8functionIFvvEEENS3_IFNS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEvEEEES7_SF_EEEvDpOT_+116)
2020-05-12 07:56:05.414 5312-5312/? A/DEBUG:     #26 pc 0000000000026700  /data/app/de.wrz.haustraum-EYwCMySKegD9LZqUkC8B5w==/lib/arm64/libhermes-executor-debug.so (facebook::react::JSIExecutor::callFunction(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const&, folly::dynamic const&)+1156)
2020-05-12 07:56:05.414 5312-5312/? A/DEBUG:     #27 pc 00000000000a2e64  /data/app/de.wrz.haustraum-EYwCMySKegD9LZqUkC8B5w==/lib/arm64/libreactnativejni.so
2020-05-12 07:56:05.414 5312-5312/? A/DEBUG:     #28 pc 00000000000a445c  /data/app/de.wrz.haustraum-EYwCMySKegD9LZqUkC8B5w==/lib/arm64/libreactnativejni.so
2020-05-12 07:56:05.414 5312-5312/? A/DEBUG:     #29 pc 00000000000698c0  /data/app/de.wrz.haustraum-EYwCMySKegD9LZqUkC8B5w==/lib/arm64/libreactnativejni.so
2020-05-12 07:56:05.414 5312-5312/? A/DEBUG:     #30 pc 000000000005a72c  /data/app/de.wrz.haustraum-EYwCMySKegD9LZqUkC8B5w==/lib/arm64/libreactnativejni.so (_ZN8facebook3jni6detail13MethodWrapperIMNS_5react15JNativeRunnableEFvvEXadL_ZNS4_3runEvEES4_vJEE8dispatchENS0_9alias_refIPNS1_8JTypeForINS0_11HybridClassIS4_NS3_8RunnableEE8JavaPartESB_vE11_javaobjectEEE+32)
2020-05-12 07:56:05.414 5312-5312/? A/DEBUG:     #31 pc 000000000005a6a8  /data/app/de.wrz.haustraum-EYwCMySKegD9LZqUkC8B5w==/lib/arm64/libreactnativejni.so (_ZN8facebook3jni6detail15FunctionWrapperIPFvNS0_9alias_refIPNS1_8JTypeForINS0_11HybridClassINS_5react15JNativeRunnableENS6_8RunnableEE8JavaPartES8_vE11_javaobjectEEEEXadL_ZNS1_13MethodWrapperIMS7_FvvEXadL_ZNS7_3runEvEES7_vJEE8dispatchESE_EESD_vJEE4callEP7_JNIEnvP8_jobject+52)
2020-05-12 07:56:05.414 5312-5312/? A/DEBUG:     #32 pc 0000000000561fe0  /system/lib64/libart.so (art_quick_generic_jni_trampoline+144)
2020-05-12 07:56:05.414 5312-5312/? A/DEBUG:     #33 pc 0000000000028140  /dev/ashmem/dalvik-jit-code-cache_5196_5196 (deleted) (android.os.Handler.handleCallback+64)
2020-05-12 07:56:05.414 5312-5312/? A/DEBUG:     #34 pc 00000000000314dc  /dev/ashmem/dalvik-jit-code-cache_5196_5196 (deleted) (android.os.Handler.dispatchMessage+60)
2020-05-12 07:56:05.414 5312-5312/? A/DEBUG:     #35 pc 000000000005bf64  /dev/ashmem/dalvik-jit-code-cache_5196_5196 (deleted) (com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage+52)
2020-05-12 07:56:05.414 5312-5312/? A/DEBUG:     #36 pc 00000000000017f0  /dev/ashmem/dalvik-jit-code-cache_5196_5196 (deleted) (android.os.Looper.loop+1200)
2020-05-12 07:56:05.414 5312-5312/? A/DEBUG:     #37 pc 000000000055924c  /system/lib64/libart.so (art_quick_invoke_static_stub+604)
2020-05-12 07:56:05.414 5312-5312/? A/DEBUG:     #38 pc 00000000000d00e8  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+232)
2020-05-12 07:56:05.414 5312-5312/? A/DEBUG:     #39 pc 0000000000280868  /system/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+344)
2020-05-12 07:56:05.414 5312-5312/? A/DEBUG:     #40 pc 000000000027a870  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+968)
2020-05-12 07:56:05.414 5312-5312/? A/DEBUG:     #41 pc 0000000000529488  /system/lib64/libart.so (MterpInvokeStatic+204)
2020-05-12 07:56:05.414 5312-5312/? A/DEBUG:     #42 pc 000000000054b794  /system/lib64/libart.so (ExecuteMterpImpl+14612)
2020-05-12 07:56:05.414 5312-5312/? A/DEBUG:     #43 pc 00000000002fa72a  /dev/ashmem/dalvik-classes2.dex extracted in memory from /data/app/de.wrz.haustraum-EYwCMySKegD9LZqUkC8B5w==/base.apk!classes2.dex_5196_5196 (deleted) (com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run+74)
2020-05-12 07:56:05.414 5312-5312/? A/DEBUG:     #44 pc 0000000000254574  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3665920253+488)
2020-05-12 07:56:05.414 5312-5312/? A/DEBUG:     #45 pc 000000000025a068  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
2020-05-12 07:56:05.415 5312-5312/? A/DEBUG:     #46 pc 000000000027a854  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+940)
2020-05-12 07:56:05.415 5312-5312/? A/DEBUG:     #47 pc 0000000000528f00  /system/lib64/libart.so (MterpInvokeInterface+1392)
2020-05-12 07:56:05.415 5312-5312/? A/DEBUG:     #48 pc 000000000054b814  /system/lib64/libart.so (ExecuteMterpImpl+14740)
2020-05-12 07:56:05.415 5312-5312/? A/DEBUG:     #49 pc 00000000000caa52  /system/framework/boot.vdex (java.lang.Thread.run+12)
2020-05-12 07:56:05.415 5312-5312/? A/DEBUG:     #50 pc 0000000000254574  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.3665920253+488)
2020-05-12 07:56:05.415 5312-5312/? A/DEBUG:     #51 pc 0000000000518818  /system/lib64/libart.so (artQuickToInterpreterBridge+1020)
2020-05-12 07:56:05.415 5312-5312/? A/DEBUG:     #52 pc 00000000005620fc  /system/lib64/libart.so (art_quick_to_interpreter_bridge+92)
2020-05-12 07:56:05.415 5312-5312/? A/DEBUG:     #53 pc 0000000000558f88  /system/lib64/libart.so (art_quick_invoke_stub+584)
2020-05-12 07:56:05.415 5312-5312/? A/DEBUG:     #54 pc 00000000000d00c8  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200)
2020-05-12 07:56:05.415 5312-5312/? A/DEBUG:     #55 pc 000000000045e8f8  /system/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104)
2020-05-12 07:56:05.415 5312-5312/? A/DEBUG:     #56 pc 000000000045f9b4  /system/lib64/libart.so (art::InvokeVirtualOrInterfaceWithJValues(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, jvalue*)+424)
2020-05-12 07:56:05.415 5312-5312/? A/DEBUG:     #57 pc 000000000048add4  /system/lib64/libart.so (art::Thread::CreateCallback(void*)+1120)
2020-05-12 07:56:05.415 5312-5312/? A/DEBUG:     #58 pc 0000000000091bd0  /system/lib64/libc.so (__pthread_start(void*)+36)
2020-05-12 07:56:05.415 5312-5312/? A/DEBUG:     #59 pc 0000000000024240  /system/lib64/libc.so (__start_thread+68)
2020-05-12 07:56:06.110 1018-1018/? E//system/bin/tombstoned: Tombstone written to: /data/tombstones/tombstone_07
2020-05-12 07:56:06.206 1382-1533/? E/InputDispatcher: channel '463184d de.wrz.haustraum/de.wrz.haustraum.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2020-05-12 07:56:06.226 1382-1419/? E/WindowManager: RemoteException occurs on reporting focusChanged, w=Window{463184d u0 de.wrz.haustraum/de.wrz.haustraum.MainActivity EXITING}
    android.os.DeadObjectException
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:1145)
        at android.view.IWindow$Stub$Proxy.windowFocusChanged(IWindow.java:500)
        at com.android.server.wm.WindowState.reportFocusChangedSerialized(WindowState.java:3981)
        at com.android.server.wm.WindowManagerService$H.handleMessage(WindowManagerService.java:5515)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:65)
        at com.android.server.ServiceThread.run(ServiceThread.java:44)
```

Running Version 1.0.0 with React-Native 0.61.5 crashes aswell:
```
[Info] 05-12 11:49:24.486 17722 17806 E ReactNativeJS: Invariant Violation: [605,"RCTView",1,{"pointerEvents":"box-none","onLayout":true,"flex":1,"paddingTop":"<<NaN>>","paddingBottom":"<<NaN>>","paddingLeft":"<<NaN>>","paddingRight":"<<NaN>>"}] is not usable as a native method argument
05-12 11:49:24.486 17722 17806 E ReactNativeJS: 
05-12 11:49:24.486 17722 17806 E ReactNativeJS: This error is located at:
05-12 11:49:24.486 17722 17806 E ReactNativeJS:     in NavigationContainer
05-12 11:49:24.486 17722 17806 E ReactNativeJS:     in NavigationContainer (at App.js:118)
05-12 11:49:24.486 17722 17806 E ReactNativeJS:     in RCTView (at App.js:116)
05-12 11:49:24.486 17722 17806 E ReactNativeJS:     in RNCSafeAreaView (at SafeAreaContext.tsx:50)
05-12 11:49:24.486 17722 17806 E ReactNativeJS:     in SafeAreaProvider (at App.js:115)
05-12 11:49:24.486 17722 17806 E ReactNativeJS:     in PersistGate (at App.js:114)
05-12 11:49:24.486 17722 17806 E ReactNativeJS:     in Provider (at App.js:113)
05-12 11:49:24.486 17722 17806 E ReactNativeJS:     in App (at renderApplication.js:40)
05-12 11:49:24.486 17722 17806 E ReactNativeJS:     in RCTView (at AppContainer.js:101)
05-12 11:49:24.486 17722 17806 E ReactNativeJS:     in RCTView (at AppContainer.js:119)
05-12 11:49:24.486 17722 17806 E ReactNativeJS:     in AppContainer (at renderApplication.js:39)
```

**Comment by janicduplessis** [comment]
Hey thanks for reporting this, seems like you are using React Navigation can you tell me what version?

**Comment by Relax594** [comment]
React-Navigation: 4.3.9

**Comment by janicduplessis** [comment]
I wasn't able to reproduce the issue. I added a react-navigation 4 example here https://github.com/th3rdwave/react-native-safe-area-context/blob/master/example/src/ReactNavigation4Example.tsx. Are you able to reproduce consistently in development?

The last stacktrace you provided is useful and it seems like the issue is that inset values are NaN / undefined but I can't figure out why. Do you have more detailled logs / stacktraces?

Also can you give me a list of all packages you use and their version? Also do you have any other usage of react-native-safe-area-context in your app except the one showed here?

**Comment by Relax594** [comment]
It happens on 5 different apps every time since upgrading. Went back to 0.7.3 for the time being.

I will create more detailed logs and send you a list of packages on Monday when I’m back at work.

No other use of react-native-Safe-area-context beside that.

**Comment by Relax594** [comment]
```
"dependencies": {
    "@react-native-community/async-storage": "^1.10.1",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-community/netinfo": "5.8.1",
    "@react-native-community/viewpager": "3.3.0",
    "@reduxjs/toolkit": "^1.3.6",
    "color": "^3.1.2",
    "lodash": "^4.17.15",
    "native-base": "^2.13.12",
    "prop-types": "^15.7.2",
    "react": "16.9.0",
    "react-hooks-use-previous": "^1.1.1",
    "react-native": "0.61.5",
    "react-native-bootsplash": "^2.2.4",
    "react-native-devsettings-android": "^0.4.0",
    "react-native-dialogs": "^1.1.0",
    "react-native-elements": "^2.0.0",
    "react-native-flash-message": "^0.1.15",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-mail": "^4.1.0",
    "react-native-material-ripple": "^0.9.1",
    "react-native-pdf": "^6.1.2",
    "react-native-reanimated": "^1.8.0",
    "react-native-safe-area-context": "^1.0.0",
    "react-native-safe-area-view": "^1.1.1",
    "react-native-screens": "^2.7.0",
    "react-native-settings-components": "^0.0.2",
    "react-native-svg": "^12.1.0",
    "react-native-svg-charts": "^5.4.0",
    "react-native-vector-icons": "^6.6.0",
    "react-navigation": "^4.3.9",
    "react-navigation-drawer": "^2.4.13",
    "react-navigation-hooks": "^1.1.0",
    "react-navigation-stack": "^2.5.1",
    "react-redux": "^7.2.0",
    "redux": "^4.0.5",
    "redux-devtools-extension": "^2.13.8",
    "redux-form": "^8.3.5",
    "redux-logger": "^3.0.6",
    "redux-persist": "^6.0.0",
    "redux-saga": "^1.1.3",
    "rn-fetch-blob": "^0.12.0"
  },
```

This is the latest log i could get. It's with the packages listed above in a different app.
```
2020-05-18 08:12:42.150 6209-6292/de.wrz.bavrechner E/ReactNativeJS: Invariant Violation: [687,"RCTView",1,{"pointerEvents":"box-none","onLayout":true,"flex":1,"paddingTop":"<<NaN>>","paddingBottom":"<<NaN>>","paddingLeft":"<<NaN>>","paddingRight":"<<NaN>>"}] is not usable as a native method argument
    
    This error is located at:
        in RCTView (at createAnimatedComponent.js:151)
        in AnimatedComponent (at src/index.tsx:85)
        in SafeAreaView (at bavRechner.js:166)
        in RCTView (at bavRechner.js:155)
        in Unknown (created by SceneView)
        in SceneView (created by CardContainer)
        in RCTView (created by CardContainer)
        in RCTView (created by CardContainer)
        in RCTView (created by ForwardRef(CardSheet))
        in ForwardRef(CardSheet) (created by Card)
        in RCTView (at createAnimatedComponent.js:151)
        in AnimatedComponent (created by PanGestureHandler)
        in PanGestureHandler (created by PanGestureHandler)
        in PanGestureHandler (created by Card)
        in RCTView (at createAnimatedComponent.js:151)
        in AnimatedComponent (created by Card)
        in RCTView (created by Card)
        in Card (created by CardContainer)
        in CardContainer (created by CardStack)
        in RNSScreen (at createAnimatedComponent.js:151)
        in AnimatedComponent (at screens.native.js:109)
        in Screen (created by MaybeScreen)
        in MaybeScreen (created by CardStack)
        in RNSScreenContainer (at screens.native.js:134)
        in ScreenContainer (created by MaybeScreenContainer)
        in MaybeScreenContainer (created by CardStack)
        in CardStack (created by KeyboardManager)
        in KeyboardManager (created by Context.Consumer)
        in SafeAreaConsumer (created by StackView)
        in SafeAreaConsumer (created by SafeAreaProviderCompat)
        in SafeAreaProviderCompat (created by StackView)
        in RCTView (at GestureHandlerRootView.android.js:26)
        in GestureHandlerRootView (created by StackView)
        in StackView (created by StackView)
        in StackView
        in Unknown (created by Navigator)
        in Navigator (created by SceneView)
        in SceneView (created by Drawer)
        in RNSScreen (at createAnimatedComponent.js:151)
        in AnimatedComponent (at screens.native.js:109)
        in Screen (created by ResourceSavingScene)
        in ResourceSavingScene (created by Drawer)
        in RNSScreenContainer (at screens.native.js:134)
        in ScreenContainer (created by Drawer)
        in RCTView (at createAnimatedComponent.js:233)
        in AnimatedComponent(Component) (created by Drawer)
        in RCTView (at createAnimatedComponent.js:233)
        in AnimatedComponent(Component) (created by PanGestureHandler)
        in PanGestureHandler (created by Drawer)
        in Drawer (created by DrawerView)
        in DrawerView (created by Navigator)
        in Navigator (created by SceneView)
        in SceneView (created by CardContainer)
        in RCTView (created by CardContainer)
        in RCTView (created by CardContainer)
        in RCTView (created by ForwardRef(CardSheet))
        in ForwardRef(CardSheet) (created by Card)
        in RCTView (at createAnimatedComponent.js:151)
        in AnimatedComponent (created by PanGestureHandler)
        in PanGestureHandler (created by PanGestureHandler)
        in PanGestureHandler (created by Card)
        in RCTView (at createAnimatedComponent.js:151)
        in AnimatedComponent (created by Card)
        in RCTView (created by Card)
        in Card (created by CardContainer)
        in CardContainer (created by CardStack)
        in RCTView (created by MaybeScreen)
        in MaybeScreen (created by CardStack)
        in RCTView (created by MaybeScreenContainer)
        in MaybeScreenContainer (created by CardStack)
        in CardStack (created by KeyboardManager)
        in KeyboardManager (created by Context.Consumer)
        in SafeAreaConsumer (created by StackView)
        in SafeAreaConsumer (created by SafeAreaProviderCompat)
        in SafeAreaProviderCompat (created by StackView)
        in GestureHandlerRootView (at GestureHandlerRootView.android.js:31)
        in GestureHandlerRootView (created by StackView)
        in StackView (created by StackView)
        in StackView
        in Unknown (created by Navigator)
        in Navigator (created by NavigationContainer)
        in Nav
2020-05-18 08:12:42.222 6209-6292/de.wrz.bavrechner E/ReactNativeJS: Invariant Violation: [687,"RCTView",1,{"pointerEvents":"box-none","onLayout":true,"flex":1,"paddingTop":"<<NaN>>","paddingBottom":"<<NaN>>","paddingLeft":"<<NaN>>","paddingRight":"<<NaN>>"}] is not usable as a native method argument
    
    This error is located at:
        in NavigationContainer
        in NavigationContainer (at App.js:104)
        in RCTView (at App.js:102)
        in RNCSafeAreaView (at SafeAreaContext.tsx:50)
        in SafeAreaProvider (at App.js:101)
        in PersistGate (at App.js:100)
        in Provider (at App.js:99)
        in App (at renderApplication.js:40)
        in RCTView (at AppContainer.js:101)
        in RCTView (at AppContainer.js:119)
        in AppContainer (at renderApplication.js:39)
2020-05-18 08:12:42.231 6209-6292/de.wrz.bavrechner E/ReactNativeJS: Invariant Violation: [687,"RCTView",1,{"pointerEvents":"box-none","onLayout":true,"flex":1,"paddingTop":"<<NaN>>","paddingBottom":"<<NaN>>","paddingLeft":"<<NaN>>","paddingRight":"<<NaN>>"}] is not usable as a native method argument
    
    This error is located at:
        in NavigationContainer
        in NavigationContainer (at App.js:104)
        in RCTView (at App.js:102)
        in RNCSafeAreaView (at SafeAreaContext.tsx:50)
        in SafeAreaProvider (at App.js:101)
        in PersistGate (at App.js:100)
        in Provider (at App.js:99)
        in App (at renderApplication.js:40)
        in RCTView (at AppContainer.js:101)
        in RCTView (at AppContainer.js:119)
        in AppContainer (at renderApplication.js:39)
```

**Comment by GertjanReynaert** [comment]
Maybe it's helpful, this is the error I have with the unstable logbox enabled:

<img width="502" alt="Screenshot 2020-05-18 at 10 49 09" src="https://user-images.githubusercontent.com/4712292/82196033-78d93180-98f9-11ea-9dae-5c1b8291a82b.png">

With these dependencies (if you need/want the full list let me know)

```
    "react": "16.13.1",
    "react-native": "0.62.2",
    "react-native-safe-area-context": "1.0.0",
    "react-native-safe-area-view": "1.1.1",
    "react-navigation": "4.3.9",
    "react-navigation-stack": "2.5.1",
    "react-navigation-tabs": "2.8.13",
```

**Comment by janicduplessis** [comment]
Ok I think I figured it out, the issue actually comes from https://github.com/react-navigation/react-native-safe-area-view. Can you try updating it to 2.0.0 see if it fixes the issue?

**Comment by janicduplessis** [comment]
I also published a new version to bring back compatibility with react-native-safe-area-view@1.0. Should be all good now!
